### PR TITLE
AVI-6: Create UI template for Employee Management page (HTML/CSS only)

### LINKED ISSUE #6: Create UI template for Employee Management page (HTML/CSS only)
### Description

Create the UI template for the Employee Management page with only HTML and CSS.

### To Do

- [x] HTML/CSS files for page design should go in the `template` folder

### Acceptance Criteria

- Page should have a table listing all the employees
- Table should display each employee information:
  - First Name
  - Last Name
  - Email address
  - Gender
  - [More to be defined]
- For each table row, there should be action buttons to `view`, `edit`, `delete` a specific employee.

### PR DESCRIPTION
**Pull request by Doyin02**
### What does this PR do

This is the PR for the management UI template.

Closes #6

#### How should it be tested
- Go to your local development, navigate to template
- Inside the template you will find a file named management.html
- NOTE: Inside the template, there is a folder named styles
- Right-click on the management.html file and open with live-server

### Screenshots

Screenshot (70)

### CODE REVIEW

**Review by harry-olabs — CHANGES_REQUESTED** [review]
# Feedback

It is looking good, however this is supposed to be part of the dashboard design and not standalone.
I have attached a design spec to follow.

Adjust the current design to match the attached design layout. Things to include:
- Let the title be "Manage Users", this also applies to the link on the dashboard sidebar
- Employee avatar
- Employee first/last name and email should be in one column according to the attached design
- Role (User type e.g Admin, HR Admin, Employee etc)
- Created date
- Title (Job Title)

Let's rename the file to `users.html`
Screenshot 2023-06-18 at 22 03 53

**Comment by Doyin02** [comment]
### How the employee management UI template looks like now
Screenshot (71)

**Comment by harry-olabs** [comment]
It is looking good, but we still missing some required changes — Will talk more over the call

A few things to do before our call:

General Feedback/Section-1:
- It looks like all the buttons do not have the font-family. Be sure to apply the font-family to all the buttons

Section-2
- The font-weight is too strong for User's name. Use the weight number as opposed using `font-weight: bold`

Section-3
- Compare the design I shared with you and what we currently have — Update it accordingly
- Let's have different color for each type

Section-4
- Add icons to the left of each action button text

Screenshot 2023-06-20 at 16 22 21

**Comment by Doyin02** [comment]
### It is now able to move from one page to another onclick on each of the first 2 sidebar links 
Screenshot (118)
Screenshot (119)

**Review by harry-olabs — APPROVED** [review]
LGTM 🚀

**Pull request merged**
