### PR TITLE
AVI-4: Create UI template for registration and login page 

### PR DESCRIPTION
**Pull request by Doyin02**
I have just created the login page for now, I want to jump on the registration page now
Screenshot (16)

### CODE REVIEW

**Comment by Doyin02** [comment]
This is the picture of the registration page 
Screenshot (19)

**Review by harry-olabs — CHANGES_REQUESTED** [review]
Good job @Doyin02, it is looking good. Just a few things to improve on:

- Let's have some space between the labels and the inputs, at least 5px of margin.
- Same way you have a folder images, let's put all the css in a `styles` folder.
- For css classes, I want you to follow a convention called the BEM convention: Read up about BEM in the [Introduction](https://getbem.com/introduction/) and [How the naming works](https://getbem.com/naming/).

**Comment by Doyin02** [comment]
I have been able to give some spacing between the label and the input field 
Screenshot (20)
and the same with the registration page also. And I have also created a folder called styles for all the css to reside

**Review by harry-olabs — APPROVED** [review]
Looks good to me 🚀

**Pull request merged**
